import { generateRandomId } from "./services/utils";

export const tasksData = [
  {
    id: generateRandomId(),
    task: "Fix website bug",
    assignee: "John Doe",
    priority: "High",
  },
  {
    id: generateRandomId(),
    task: "Prepare monthly report",
    assignee: "Alice Smith",
    priority: "Medium",
  },
  {
    id: generateRandomId(),
    task: "Client meeting",
    assignee: "Bob Johnson",
    priority: "Low",
  },
  {
    id: generateRandomId(),
    task: "Design new landing page",
    assignee: "Sarah Lee",
    priority: "High",
  },
  {
    id: generateRandomId(),
    task: "Update social media posts",
    assignee: "David Kim",
    priority: "Low",
  },
  {
    id: generateRandomId(),
    task: "Review marketing strategy",
    assignee: "Chris Brown",
    priority: "Medium",
  },
  {
    id: generateRandomId(),
    task: "Organize team event",
    assignee: "Emily Clark",
    priority: "High",
  },
  {
    id: generateRandomId(),
    task: "Refactor codebase",
    assignee: "Michael Scott",
    priority: "Medium",
  },
  {
    id: generateRandomId(),
    task: "Audit financial records",
    assignee: "Rachel Green",
    priority: "High",
  },
  {
    id: generateRandomId(),
    task: "Customer feedback follow-up",
    assignee: "Monica Geller",
    priority: "Low",
  },
  {
    id: generateRandomId(),
    task: "Schedule project presentation",
    assignee: "Angela Martin",
    priority: "Medium",
  },
  {
    id: generateRandomId(),
    task: "Research new tools",
    assignee: "Dwight Schrute",
    priority: "High",
  },
  {
    id: generateRandomId(),
    task: "Team building workshop",
    assignee: "Pam Beesly",
    priority: "Low",
  },
  {
    id: generateRandomId(),
    task: "Code review session",
    assignee: "Jim Halpert",
    priority: "High",
  },
  {
    id: generateRandomId(),
    task: "Security audit",
    assignee: "Stanley Hudson",
    priority: "Medium",
  },
  {
    id: generateRandomId(),
    task: "User feedback analysis",
    assignee: "Kelly Kapoor",
    priority: "Low",
  },
  {
    id: generateRandomId(),
    task: "Test new app features",
    assignee: "Ryan Howard",
    priority: "High",
  },
  {
    id: generateRandomId(),
    task: "Redesign mobile app UI",
    assignee: "Creed Bratton",
    priority: "Medium",
  },
  {
    id: generateRandomId(),
    task: "Setup new project repository",
    assignee: "Oscar Martinez",
    priority: "Low",
  },
  {
    id: generateRandomId(),
    task: "Develop sales pitch",
    assignee: "Phyllis Vance",
    priority: "High",
  },
  {
    id: generateRandomId(),
    task: "Prepare contract documentation",
    assignee: "Toby Flenderson",
    priority: "Medium",
  },
  {
    id: generateRandomId(),
    task: "Improve API performance",
    assignee: "Darryl Philbin",
    priority: "Low",
  },
  {
    id: generateRandomId(),
    task: "Create onboarding materials",
    assignee: "Meredith Palmer",
    priority: "High",
  },
  {
    id: generateRandomId(),
    task: "Optimize SEO strategy",
    assignee: "Jan Levinson",
    priority: "Medium",
  },
  {
    id: generateRandomId(),
    task: "Test backup systems",
    assignee: "Roy Anderson",
    priority: "Low",
  },
  {
    id: generateRandomId(),
    task: "Migrate to cloud infrastructure",
    assignee: "Holly Flax",
    priority: "High",
  },
  {
    id: generateRandomId(),
    task: "Update documentation",
    assignee: "Kevin Malone",
    priority: "Medium",
  },
  {
    id: generateRandomId(),
    task: "Design new company logo",
    assignee: "Erin Hannon",
    priority: "Low",
  },
  {
    id: generateRandomId(),
    task: "Prepare year-end financial report",
    assignee: "Andy Bernard",
    priority: "High",
  },
  {
    id: generateRandomId(),
    task: "Organize product launch",
    assignee: "Gabe Lewis",
    priority: "Medium",
  },
];
